name: Deploy

on:
  pull_request:
    branches: ["main"]
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd activepieces
            git pull origin main
            docker compose -f docker-compose.niqat.yml -p activepieces down
            docker compose -f docker-compose.niqat.yml -p activepieces up -d --build
            docker image prune -f
            docker container prune -f
          command_timeout: 3600s
