name: Deploy to Server

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: SSH and run docker command
        run: |
          expect <<'EOF'
          spawn ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          expect "assword:"
          send "${{ secrets.SSH_PASSWORD }}\r"
          expect "$ "
          send "cd activepieces && docker compose -f docker-compose.niqat.yml -p activepieces down && git pull && docker compose -f docker-compose.niqat.yml -p activepieces up -d --build\r"
          expect "$ "
          send "exit\r"
          expect eof
          EOF
